#!/usr/bin/env bash
# Shared helpers for the PPFlight PDF Agent administrative scripts.
set -Eeuo pipefail

readonly APP_NAME="ppflight-pdf-agent"
readonly SERVICE_NAME="ppflight-pdf-agent.service"
readonly SERVICE_USER="ppflight-pdf"
readonly APP_ROOT="/opt/${APP_NAME}"
# Used by lifecycle scripts that source this library; ShellCheck also analyzes
# this file as a standalone target in CI.
# shellcheck disable=SC2034
readonly RELEASES_DIR="${APP_ROOT}/releases"
readonly CURRENT_LINK="${APP_ROOT}/current"
readonly CONFIG_DIR="/etc/${APP_NAME}"
readonly CONFIG_FILE="${CONFIG_DIR}/config.json"
readonly INSTALL_ENV="${CONFIG_DIR}/install.env"
readonly STATE_DIR="/var/lib/${APP_NAME}"
# shellcheck disable=SC2034
readonly UNIT_FILE="/etc/systemd/system/${SERVICE_NAME}"
readonly LOCK_FILE="/var/lock/${APP_NAME}.lock"

die() { echo "${APP_NAME}: $*" >&2; exit 1; }
note() { echo "${APP_NAME}: $*" >&2; }

require_root() {
  [[ ${EUID} -eq 0 ]] || die "run this command as root"
}

require_linux_distribution() {
  [[ -r /etc/os-release ]] || die "only Debian 12 and supported Ubuntu releases are supported"
  # shellcheck disable=SC1091
  . /etc/os-release
  case "${ID:-}" in
    debian) [[ "${VERSION_ID:-}" == "12" ]] || die "Debian 12 is required" ;;
    ubuntu) : ;; # Python/PHP versions are checked independently below.
    *) die "only Debian 12 and Ubuntu are supported" ;;
  esac
}

take_lock() {
  # update.sh invokes the downloaded install.sh while retaining this lock. The
  # child inherits fd 9, so it must lock that same open file description rather
  # than open a second descriptor and deadlock against its parent.
  if [[ "${PPFLIGHT_PDF_LOCK_HELD:-}" == "1" ]]; then
    flock -n 9 || die "inherited lifecycle lock is unavailable"
    return
  fi
  install -d -m 0755 /var/lock
  exec 9>"${LOCK_FILE}"
  flock -n 9 || die "another install, update, rollback or uninstall is running"
}

source_dir_of() {
  cd -P "$(dirname "${BASH_SOURCE[1]}")" && pwd
}

absolute_dir() {
  local target=$1 resolved
  [[ -n "${target}" && ! -L "${target}" ]] || die "artifact directory must not be empty or a symlink"
  resolved="$(realpath -m -- "${target}")"
  [[ "${resolved}" =~ ^/[A-Za-z0-9._/@+=-]+$ ]] || \
    die "artifact directory contains characters unsafe for JSON or systemd templates"
  case "${resolved}" in
    /|/bin|/boot|/dev|/etc|/home|/lib|/lib64|/proc|/root|/run|/sbin|/sys|/tmp|/usr|/var|/www|/WWW|\
    /bin/*|/boot/*|/dev/*|/etc/*|/home/*|/lib/*|/lib64/*|/proc/*|/root/*|/run/*|/sbin/*|/sys/*|/tmp/*|/usr/*|/var/tmp/*)
      die "artifact directory points at a protected or ephemeral filesystem path"
      ;;
  esac
  mkdir -p -- "${resolved}"
  [[ -d "${resolved}" && ! -L "${resolved}" ]] || die "artifact directory must resolve to a real directory"
  cd -P -- "${resolved}" && pwd
}

sed_replacement() {
  # Artifact paths are normalized before this point; escape the remaining
  # characters meaningful to the systemd/config template substitution.
  printf '%s' "$1" | sed 's/[&|]/\\&/g'
}

atomic_symlink() {
  local target=$1 link=$2 temporary
  temporary="${link}.new.$$"
  ln -s -- "${target}" "${temporary}"
  mv -Tf -- "${temporary}" "${link}"
}

current_release() {
  [[ -L "${CURRENT_LINK}" ]] || return 1
  readlink -f -- "${CURRENT_LINK}"
}

artifact_dir_from_install_env() {
  [[ -r "${INSTALL_ENV}" ]] || return 1
  # install.env is root-owned and generated by this installer; only accept a
  # simple quoted value to avoid evaluating configuration as shell code.
  sed -n 's/^PDF_AGENT_ARTIFACT_DIR=//p' "${INSTALL_ENV}" | head -n 1
}

write_install_env_if_missing() {
  local artifact_dir=$1 temp
  [[ -e "${INSTALL_ENV}" ]] && return 0
  temp="${INSTALL_ENV}.new.$$"
  umask 077
  printf 'PDF_AGENT_ARTIFACT_DIR=%s\n' "${artifact_dir}" >"${temp}"
  chown root:"${SERVICE_USER}" "${temp}"
  chmod 0640 "${temp}"
  mv -f -- "${temp}" "${INSTALL_ENV}"
}

ensure_service_account() {
  if ! getent group "${SERVICE_USER}" >/dev/null; then
    groupadd --system "${SERVICE_USER}"
  fi
  if ! id -u "${SERVICE_USER}" >/dev/null 2>&1; then
    useradd --system --gid "${SERVICE_USER}" --home-dir "${STATE_DIR}" \
      --shell /usr/sbin/nologin --comment "PPFlight PDF Agent" "${SERVICE_USER}"
  fi
}

ensure_runtime_dirs() {
  local artifact_dir=$1
  install -d -m 0750 -o "${SERVICE_USER}" -g "${SERVICE_USER}" "${STATE_DIR}"
  [[ -d "${artifact_dir}" && ! -L "${artifact_dir}" ]] || die "artifact directory is not a real directory"
  # Never take ownership of a populated directory that belongs to another
  # account. This prevents a typo such as --artifact-dir /srv from turning a
  # broad existing tree into service-owned data.
  if [[ "$(stat -c '%U' "${artifact_dir}")" != "${SERVICE_USER}" ]] && \
     find "${artifact_dir}" -mindepth 1 -maxdepth 1 -print -quit | grep -q .; then
    die "refusing to take ownership of a populated artifact directory"
  fi
  chown "${SERVICE_USER}:${SERVICE_USER}" "${artifact_dir}"
  chmod 0750 "${artifact_dir}"
}

python_and_php_ok() {
  command -v python3 >/dev/null || return 1
  command -v php >/dev/null || return 1
  command -v composer >/dev/null || return 1
  python3 -c 'import sys; raise SystemExit(sys.version_info < (3, 9))' || return 1
  php -r 'exit(version_compare(PHP_VERSION, "8.2.0", ">=") ? 0 : 1);' || return 1
  local extension
  for extension in mbstring xml gd; do
    php -m | grep -Fxq "${extension}" || return 1
  done
}

install_dependencies() {
  require_linux_distribution
  export DEBIAN_FRONTEND=noninteractive
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates curl composer python3 python3-pip python3-venv \
    php-cli php-mbstring php-xml php-gd
}

health_check() {
  local attempts=15
  local attempt
  for ((attempt = 1; attempt <= attempts; attempt++)); do
    if curl --fail --silent --show-error --max-time 3 http://127.0.0.1:9760/healthz >/dev/null; then
      return 0
    fi
    sleep 1
  done
  return 1
}

post_start_check() {
  health_check || return 1
  # A first installation cannot yet authenticate to ADMIN. Once binding state
  # exists, verify both the local listener and a real authenticated heartbeat.
  if [[ -s "${STATE_DIR}/state.json" ]]; then
    local release
    release="$(current_release)" || return 1
    runuser -u "${SERVICE_USER}" -- "${release}/.venv/bin/python" \
      "${release}/agent.py" --config "${CONFIG_FILE}" check >/dev/null
  fi
}
